In [1]:
print('ok')

ok


In [1]:
import numpy as np

In [25]:
import numpy as np

# Set the file path
data_gt = r'C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\4e670b56-00082-pano1.txt'
pred_mask  = r'C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\4e670b56-00082-pano.txt'

# Load the file as a numpy array
gt_mask = np.loadtxt(data_gt, dtype=np.int32 )
pred_mask  = np.loadtxt(pred_mask, dtype=np.int32 )

# Print the resulting numpy array
print(gt_mask , pred_mask  )


[[0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]] [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


C:\Users\jen_bim-y\AppData\Local\Temp\ipykernel_9852\1318224686.py:8: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  gt_mask = np.loadtxt(data_gt, dtype=np.int32 )
C:\Users\jen_bim-y\AppData\Local\Temp\ipykernel_9852\1318224686.py:9: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the fil

In [26]:
pred_mask = np.resize(pred_mask, gt_mask.shape)

In [27]:
# Compute confusion matrix
num_classes = np.max(gt_mask) + 1
confusion_matrix = np.bincount(num_classes * gt_mask.ravel() + pred_mask.ravel(), minlength=num_classes**2).reshape(num_classes, num_classes)


In [28]:
# Compute IoU for each class
iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))


In [29]:
mean_iou = np.mean(iou)

In [30]:
print(mean_iou)

0.5361635220125787


# IOU with different txt

In [28]:
import numpy as np

# Set the file path
data_gt = r'C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\New\4e670b56-00082-pano.txt'
pred_mask  = r'C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\New\00735-pano.txt'

# Load the file as a numpy array
gt_mask = np.loadtxt(data_gt )
pred_mask  = np.loadtxt(pred_mask, usecols=(0,),dtype=np.int32)
print(gt_mask)
print(pred_mask)

[[0.         0.45208655 0.51313756 0.48145286 0.51313756 0.48299845
  0.61514683 0.45904173 0.6244204 ]
 [1.         0.36553323 0.27357032 0.39103555 0.26893354 0.40417311
  0.29057187 0.38176198 0.30911901]
 [1.         0.10896445 0.16692427 0.16460587 0.12055641 0.17697063
  0.187017   0.13678516 0.20710974]
 [1.         0.58809892 0.3137558  0.60587326 0.29366306 0.61746522
  0.31066461 0.60432767 0.3431221 ]
 [1.         0.73956723 0.26893354 0.76275116 0.26893354 0.77047913
  0.2488408  0.74188563 0.23493045]
 [1.         0.85394127 0.32612056 0.86398764 0.34003091 0.87712519
  0.32457496 0.86553323 0.30448223]]
[1 1 1 1 1]


In [6]:
import numpy as np

# Set the file path
data_gt = r'C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\New\4e670b56-00082-pano.txt'
pred_mask  = r'C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\New\00735-pano.txt'

# Load the file as a numpy array
gt_mask = np.loadtxt(data_gt )
pred_mask  = np.loadtxt(pred_mask, usecols=(0,),dtype=np.int32)
print(gt_mask)
print(pred_mask)


[[0.         0.45208655 0.51313756 0.48145286 0.51313756 0.48299845
  0.61514683 0.45904173 0.6244204 ]
 [1.         0.36553323 0.27357032 0.39103555 0.26893354 0.40417311
  0.29057187 0.38176198 0.30911901]
 [1.         0.10896445 0.16692427 0.16460587 0.12055641 0.17697063
  0.187017   0.13678516 0.20710974]
 [1.         0.58809892 0.3137558  0.60587326 0.29366306 0.61746522
  0.31066461 0.60432767 0.3431221 ]
 [1.         0.73956723 0.26893354 0.76275116 0.26893354 0.77047913
  0.2488408  0.74188563 0.23493045]
 [1.         0.85394127 0.32612056 0.86398764 0.34003091 0.87712519
  0.32457496 0.86553323 0.30448223]]
[1 1 1 1 1]


In [8]:
import numpy as np

# Set the file path
data_gt = r'C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\New\4e670b56-00082-pano.txt'
pred_mask  = r'C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\New\00735-pano.txt'

# Load the file as a numpy array
gt_mask = np.loadtxt(data_gt, dtype=np.int32 )
pred_mask  = np.loadtxt(pred_mask, usecols=(0,), dtype=np.int32 )

# Print the resulting numpy array
pred_mask = np.resize(pred_mask, gt_mask.shape)
# Compute confusion matrix
num_classes = np.max(gt_mask) + 1
confusion_matrix = np.bincount(num_classes * gt_mask.ravel() + pred_mask.ravel(), minlength=num_classes**2).reshape(num_classes, num_classes)
# Compute IoU for each class
mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))

print(mean_iou)

[0.         0.09259259]


C:\Users\jen_bim-y\AppData\Local\Temp\ipykernel_15124\1655618203.py:8: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  gt_mask = np.loadtxt(data_gt, dtype=np.int32 )


In [32]:
import numpy as np
import os

# Set the file paths for the training and test sets
train_path = r"C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\train"
test_path = r"C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\test"

# Loop over the training images and compute IoU scores
for train_image in os.listdir(train_path):
    for test_image in os.listdir(test_path):
        # Load the ground truth and predicted masks for the current image
        gt_mask = np.loadtxt(os.path.join(train_path, train_image ), usecols=(0,), dtype=np.int32)
        pred_mask = np.loadtxt(os.path.join(test_path, test_image), usecols=(0,), dtype=np.int32)
        #print(gt_mask,pred_mask)
        # Compute the IoU score for the current image
        pred_mask = np.resize(pred_mask, gt_mask.shape)
        # Compute confusion matrix
        num_classes = np.max(gt_mask) + 1
        confusion_matrix = np.bincount(num_classes * gt_mask.ravel() + pred_mask.ravel(), minlength=num_classes**2).reshape(num_classes, num_classes)
        # Compute IoU for each class
        mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))

        print(mean_iou)


[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[0.   0.75]
[0.   0.75]
[0.   0.75]
[0.   0.75]
[0.         0.14285714]
[0.         0.14285714]
[0.         0.14285714]
[0.         0.14285714]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[0.  0.8]
[0.  0.8]
[0.  0.8]
[0.  0.8]
[0.  0.5]
[0.  0.5]
[0.  0.5]
[0.  0.5]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]


C:\Users\jen_bim-y\AppData\Local\Temp\ipykernel_15124\2247782915.py:21: RuntimeWarning: invalid value encountered in divide
  mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))


In [30]:
import numpy as np
import os

# Set the file paths for the training and test sets
train_path = r"C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\train"
test_path = r"C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\test"

# Loop over the training images and compute IoU scores
for train_image in os.listdir(train_path):
    # Load the ground truth mask for the current training image
    gt_mask = np.loadtxt(os.path.join(train_path, train_image), usecols=(0,), dtype=np.int32)
    # Loop over the test images and compute IoU scores
    for test_image in os.listdir(test_path):
        # Load the predicted mask for the current test image
        pred_mask = np.loadtxt(os.path.join(test_path, test_image), usecols=(0,), dtype=np.int32)
        # Resize the predicted mask to match the ground truth mask
        pred_mask = np.resize(pred_mask, gt_mask.shape)
        # Compute the IoU score for the current image pair
        num_classes = np.max(gt_mask) + 1
        confusion_matrix = np.bincount(num_classes * gt_mask.ravel() + pred_mask.ravel(), minlength=num_classes**2).reshape(num_classes, num_classes)
        mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))
        print(mean_iou)


[0.         0.83333333]
[0.         0.83333333]
[0.         0.83333333]
[0.         0.83333333]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]
[0.         0.85714286]
[0.         0.85714286]
[0.         0.85714286]
[0.         0.85714286]
[nan  1.]
[nan  1.]
[nan  1.]
[nan  1.]


C:\Users\jen_bim-y\AppData\Local\Temp\ipykernel_15124\352139809.py:21: RuntimeWarning: invalid value encountered in divide
  mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))


In [33]:
import numpy as np
import os

# Set the file paths for the training and test sets
train_path = r"C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\train"
test_path = r"C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\test"

# Loop over the training images and compute IoU scores
for train_image in os.listdir(train_path):
    for test_image in os.listdir(test_path):
        # Load the ground truth and predicted masks for the current image
        gt_mask = np.loadtxt(os.path.join(train_path, train_image ), usecols=(0,), dtype=np.int32)
        pred_mask = np.loadtxt(os.path.join(test_path, test_image), usecols=(0,), dtype=np.int32)
        
        # Compute the IoU score for the current image
        pred_mask = np.resize(pred_mask, gt_mask.shape)
        # Compute confusion matrix
        num_classes = np.max(gt_mask) + 1
        confusion_matrix = np.bincount(num_classes * gt_mask.ravel() + pred_mask.ravel(), minlength=num_classes**2).reshape(num_classes, num_classes)
        # Compute IoU for each class
        mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))
        
        # Print the file name and mean IoU score
        print(f"File: {train_image} - {test_image} | Mean IoU: {mean_iou}")


File: 04a31e61-00071-pano.txt - 04a31e61-00071-pano.txt | Mean IoU: [nan  1.]
File: 04a31e61-00071-pano.txt - 0cf06555-00090-pano.txt | Mean IoU: [nan  1.]
File: 04a31e61-00071-pano.txt - 1dd55b34-00081-pano.txt | Mean IoU: [nan  1.]
File: 04a31e61-00071-pano.txt - 2e3259a6-00004-pano.txt | Mean IoU: [nan  1.]
File: 0cf06555-00090-pano.txt - 04a31e61-00071-pano.txt | Mean IoU: [0.   0.75]
File: 0cf06555-00090-pano.txt - 0cf06555-00090-pano.txt | Mean IoU: [0.   0.75]
File: 0cf06555-00090-pano.txt - 1dd55b34-00081-pano.txt | Mean IoU: [0.   0.75]
File: 0cf06555-00090-pano.txt - 2e3259a6-00004-pano.txt | Mean IoU: [0.   0.75]
File: 1dd55b34-00081-pano.txt - 04a31e61-00071-pano.txt | Mean IoU: [0.         0.14285714]
File: 1dd55b34-00081-pano.txt - 0cf06555-00090-pano.txt | Mean IoU: [0.         0.14285714]
File: 1dd55b34-00081-pano.txt - 1dd55b34-00081-pano.txt | Mean IoU: [0.         0.14285714]
File: 1dd55b34-00081-pano.txt - 2e3259a6-00004-pano.txt | Mean IoU: [0.         0.14285714]


C:\Users\jen_bim-y\AppData\Local\Temp\ipykernel_15124\284545094.py:21: RuntimeWarning: invalid value encountered in divide
  mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))


### check IOU between txt for Train and Val

In [62]:
import numpy as np
import os

# Set the file paths for the training and test sets
train_path = r"C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\train"
test_path = r"C:\Users\jen_bim-y\Desktop\Desktop\test_IOU\test"

# Loop over the training images and compute IoU scores
for train_image in os.listdir(train_path):
    for test_image in os.listdir(test_path):
        # Load the ground truth and predicted masks for the current image
        gt_mask = np.loadtxt(os.path.join(train_path, train_image ), usecols=(0,), dtype=np.int32)
        pred_mask = np.loadtxt(os.path.join(test_path, test_image), usecols=(0,), dtype=np.int32)
        
        # Compute the IoU score for the current image
        pred_mask = np.resize(pred_mask, gt_mask.shape)
        # Compute confusion matrix
        class_names = ['door', 'light']
        num_classes = np.max(gt_mask) + 1
        confusion_matrix = np.bincount(num_classes * gt_mask.ravel() + pred_mask.ravel(), minlength=num_classes**2).reshape(num_classes, num_classes)
        # Compute IoU for each class
        mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))
        #for i, iou in enumerate(mean_iou):
        #    print(f"Class: {class_names[i]} | Mean IoU: {iou*100:.2f}%")
        # Print the file name and mean IoU score
        # Loop over the mean IoU scores for each class
        #print(f"File: {train_image} - {test_image}")
        print(f"File: {train_image} - {test_image} | Mean IoU: {mean_iou}")
        for i, iou_score in enumerate(mean_iou):
            #print(f"Class {i}: {iou_score * 100:.2f}%")
            print(f"Class: {class_names[i]} : {iou_score * 100:.2f} %")
            #print(f"Class: {class_names[i]} | Mean IoU: {iou*100:.2f}%")
        print('------------------------------')


File: 04a31e61-00071-pano.txt - 04a31e61-00071-pano.txt | Mean IoU: [nan  1.]
Class: door : nan %
Class: light : 100.00 %
------------------------------
File: 04a31e61-00071-pano.txt - 0cf06555-00090-pano.txt | Mean IoU: [nan  1.]
Class: door : nan %
Class: light : 100.00 %
------------------------------
File: 04a31e61-00071-pano.txt - 1dd55b34-00081-pano.txt | Mean IoU: [nan  1.]
Class: door : nan %
Class: light : 100.00 %
------------------------------
File: 04a31e61-00071-pano.txt - 2e3259a6-00004-pano.txt | Mean IoU: [nan  1.]
Class: door : nan %
Class: light : 100.00 %
------------------------------
File: 0cf06555-00090-pano.txt - 04a31e61-00071-pano.txt | Mean IoU: [0.   0.75]
Class: door : 0.00 %
Class: light : 75.00 %
------------------------------
File: 0cf06555-00090-pano.txt - 0cf06555-00090-pano.txt | Mean IoU: [0.   0.75]
Class: door : 0.00 %
Class: light : 75.00 %
------------------------------
File: 0cf06555-00090-pano.txt - 1dd55b34-00081-pano.txt | Mean IoU: [0.   0.75

C:\Users\jen_bim-y\AppData\Local\Temp\ipykernel_13628\1639976675.py:22: RuntimeWarning: invalid value encountered in divide
  mean_iou = np.diag(confusion_matrix) / (np.sum(confusion_matrix, axis=1) + np.sum(confusion_matrix, axis=0) - np.diag(confusion_matrix))
